import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CheckCircle2, PackagePlus, ShieldAlert } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { api } from "../lib/api";
import type { Movement, MovementType, Product, Supplier } from "../types";

const movementOptions: { value: MovementType; label: string; help: string }[] = [
  { value: "STOCK_IN", label: "Stock received", help: "New units arrived" }, { value: "SALE", label: "Sale", help: "Units sold" }, { value: "DAMAGED", label: "Damaged", help: "Remove damaged units" }, { value: "ADJUSTMENT_IN", label: "Adjust up", help: "Manager correction" }, { value: "ADJUSTMENT_OUT", label: "Adjust down", help: "Manager correction" },
];
export function InventoryPage() {
  const { user } = useAuth(); const [params] = useSearchParams(); const queryClient = useQueryClient();
  const products = useQuery({ queryKey: ["products", "movement"], queryFn: () => api<{ items: Product[] }>("/products?pageSize=100") });
  const suppliers = useQuery({ queryKey: ["suppliers"], queryFn: () => api<{ items: Supplier[] }>("/reference/suppliers") });
  const [form, setForm] = useState({ productId: params.get("productId") ?? "", type: "STOCK_IN" as MovementType, quantity: 1, supplierId: "", reason: "" }); const [success, setSuccess] = useState<Movement | null>(null);
  const availableOptions = movementOptions.filter((option) => user?.role === "MANAGER" || !option.value.startsWith("ADJUSTMENT"));
  const selected = products.data?.items.find((item) => item.id === form.productId);
  const mutation = useMutation({ mutationFn: () => api<{ movement: Movement }>("/inventory/movements", { method: "POST", body: JSON.stringify({ productId: form.productId, type: form.type, quantity: Number(form.quantity), ...(form.supplierId ? { supplierId: form.supplierId } : {}), ...(form.reason ? { reason: form.reason } : {}) }) }), onSuccess: (data) => { setSuccess(data.movement); queryClient.invalidateQueries(); } });
  function submit(event: FormEvent) { event.preventDefault(); setSuccess(null); mutation.mutate(); }
  return <div className="form-split stagger-in"><section className="panel form-panel"><div className="form-heading"><span>Normal workflow</span><h2>Every unit, accounted for</h2><p>This form works independently of the AI assistant.</p></div><form className="data-form" onSubmit={submit}><label>Product<select value={form.productId} onChange={(e) => setForm({...form, productId:e.target.value})} required><option value="">Select a product</option>{products.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.quantity} available</option>)}</select></label><div className="movement-choice">{availableOptions.map((option) => <button type="button" key={option.value} className={form.type === option.value ? "selected" : ""} onClick={() => setForm({...form, type:option.value})}><strong>{option.label}</strong><small>{option.help}</small></button>)}</div><div className="form-grid"><label>Quantity<input type="number" min="1" value={form.quantity} onChange={(e) => setForm({...form, quantity:Number(e.target.value)})} required /></label><label>Supplier (optional)<select value={form.supplierId} onChange={(e) => setForm({...form, supplierId:e.target.value})}><option value="">No supplier</option>{suppliers.data?.items.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label></div><label>Reason or note<textarea rows={3} value={form.reason} onChange={(e) => setForm({...form, reason:e.target.value})} required={form.type.startsWith("ADJUSTMENT")} /></label>{mutation.error && <p className="form-error"><ShieldAlert size={17}/>{mutation.error.message}</p>}<button className="primary-button wide" disabled={mutation.isPending}><PackagePlus size={18}/>{mutation.isPending ? "Recording safely…" : "Record movement"}<ArrowRight size={18}/></button></form></section><aside className="preview-panel"><span className="preview-label">Live preview</span><div className="preview-product"><span>{selected?.name.slice(0,2).toUpperCase() || "?"}</span><div><strong>{selected?.name || "Choose a product"}</strong><small>{selected?.sku || "Stock calculation appears here"}</small></div></div><div className="quantity-preview"><span><small>Current</small><strong>{selected?.quantity ?? "—"}</strong></span><ArrowRight/><span><small>After</small><strong>{selected ? Math.max(0, selected.quantity + (["STOCK_IN","ADJUSTMENT_IN"].includes(form.type) ? form.quantity : -form.quantity)) : "—"}</strong></span></div>{success && <div className="success-card"><CheckCircle2/><div><strong>Movement recorded</strong><p>{success.beforeQuantity} → {success.afterQuantity}. The audit history has been updated.</p></div></div>}<p className="safety-note"><ShieldAlert size={16}/> The backend blocks any movement that would take stock below zero.</p></aside></div>;
}
