import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Save } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api } from "../lib/api";
import type { Category, Product } from "../types";

export function ProductFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const editing = Boolean(id);
  const categories = useQuery({ queryKey: ["categories"], queryFn: () => api<{ items: Category[] }>("/reference/categories") });
  const product = useQuery({ queryKey: ["product", id], queryFn: () => api<{ product: Product }>(`/products/${id}`), enabled: editing });
  const [form, setForm] = useState({ sku: "", name: "", description: "", categoryId: "", lowStockThreshold: 5, sellingPrice: "", costPrice: "", isActive: true });
  useEffect(() => { const item = product.data?.product; if (item) setForm({ sku: item.sku, name: item.name, description: item.description ?? "", categoryId: item.category.id, lowStockThreshold: item.lowStockThreshold, sellingPrice: String(item.sellingPriceMinor / 100), costPrice: String((item.costPriceMinor ?? 0) / 100), isActive: item.isActive }); }, [product.data]);
  const save = useMutation({ mutationFn: () => api<{ product: Product }>(editing ? `/products/${id}` : "/products", { method: editing ? "PATCH" : "POST", body: JSON.stringify({ sku: form.sku, name: form.name, description: form.description || null, categoryId: form.categoryId, lowStockThreshold: Number(form.lowStockThreshold), sellingPriceMinor: Math.round(Number(form.sellingPrice) * 100), costPriceMinor: Math.round(Number(form.costPrice) * 100), ...(editing ? { isActive: form.isActive } : {}) }) }), onSuccess: (data) => { queryClient.invalidateQueries({ queryKey: ["products"] }); navigate(`/products/${data.product.id}`); } });
  function submit(event: FormEvent) { event.preventDefault(); save.mutate(); }
  return <section className="form-panel panel stagger-in"><Link to={id ? `/products/${id}` : "/products"} className="back-link"><ArrowLeft size={17}/> Back</Link><div className="form-heading"><span>{editing ? "Manager edit" : "New catalogue item"}</span><h2>{editing ? "Refine product details" : "Add a product"}</h2><p>Prices are stored securely in paisa and shown as PKR.</p></div><form className="data-form" onSubmit={submit}><div className="form-grid"><label>Product name<input value={form.name} onChange={(e) => setForm({...form, name:e.target.value})} required /></label><label>SKU<input value={form.sku} onChange={(e) => setForm({...form, sku:e.target.value})} required /></label><label>Category<select value={form.categoryId} onChange={(e) => setForm({...form, categoryId:e.target.value})} required><option value="">Choose category</option>{categories.data?.items.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Low-stock threshold<input type="number" min="0" value={form.lowStockThreshold} onChange={(e) => setForm({...form, lowStockThreshold:Number(e.target.value)})} required /></label><label>Selling price (PKR)<input type="number" min="0" step="0.01" value={form.sellingPrice} onChange={(e) => setForm({...form, sellingPrice:e.target.value})} required /></label><label>Cost price (PKR)<input type="number" min="0" step="0.01" value={form.costPrice} onChange={(e) => setForm({...form, costPrice:e.target.value})} required /></label></div><label>Description<textarea rows={4} value={form.description} onChange={(e) => setForm({...form, description:e.target.value})} /></label>{editing && <label className="toggle-label"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({...form, isActive:e.target.checked})}/><span/> Product is active</label>}{save.error && <p className="form-error">{save.error.message}</p>}<button className="primary-button" disabled={save.isPending}><Save size={17}/> {save.isPending ? "Saving…" : "Save product"}</button></form></section>;
}

